### ISSUE TITLE
add a footer

### ISSUE THREAD

**Issue by suhani1804** [CareerDevelopmentHub/SocialHub#2]

**Comment by Ayush05m** [comment]
I wanna work on this issue. Assign me this issue.
Provide more details on what type of footer you want and specify any design if you have something particular in mind.

**Comment by Ayush05m** [comment]
And I can see you already have a footer with @2023 social hub and all rights reserved <tag>.
Specify if wanna change something.

**Comment by suhani1804** [comment]
> And I can see you already have a footer with @2023 social hub and all rights reserved . Specify if wanna change something.

include about the page, contact links and other relevant content as per your understanding.

**Comment by suhani1804** [comment]
> And I can see you already have a footer with @2023 social hub and all rights reserved . Specify if wanna change something.

Is it done?

**Comment by suhani1804** [comment]
There is no assignees from now. Everyone can contribute

**Comment by kom-senapati** [comment]
I want to solve this issue.

**Comment by suhani1804** [comment]
sure you can contribute
