### ISSUE TITLE
Create contact page 

### ISSUE THREAD

**Issue by suhani1804** [CareerDevelopmentHub/SocialHub#34]
where you have to design a page for getting messages or feedback via my mail ( for mail integration - suhanimohanty402@gmail.com)

**Comment by burhanharoon** [comment]
Hi @suhani1804, could you also assign this to me :")

**Comment by suhani1804** [comment]
> Hi @suhani1804, could you also assign this to me :")

I assigned u please do your changes by tomorrow 😊

**Comment by burhanharoon** [comment]
Hey @suhani1804, I've noticed that PRs are being merged by people who weren't assigned to the respective issues. That's not how things are usually done in open-source projects. PRs should only be merged by the person who was assigned to that particular issue. If there's any change in the plan, it should be communicated in the comments. Also, [this](https://github.com/CareerDevelopmentHub/SocialHub/issues/35) issue was assigned to me, but someone else's PR got merged. Can you please take a look into this? Thanks a lot!

**Comment by suhani1804** [comment]
Yes assigned you and gave you a timeline to complete but didn't get any response or PR from your end so I had to consider other's requests. If they are putting their efforts towards it then I can ignore their PRs.
