### ISSUE TITLE
Fix the card size 

### ISSUE THREAD

**Issue by suhani1804** [CareerDevelopmentHub/SocialHub#35]

**Comment by burhanharoon** [comment]
Hi @suhani1804, could you give me more details about the issue and assign it to me? I'd love to take a crack at it. Thanks!

**Comment by suhani1804** [comment]
> Hi @suhani1804, could you give me more details about the issue and assign it to me? I'd love to take a crack at it. Thanks!

You can see in live website that about me cards are not arrange properly in terms of size. I'll be better if you can fix it. Thank you

**Comment by Jaimin25** [comment]
What fixes does the card require? Can you provide more details about it?

**Comment by suhani1804** [comment]
> What fixes does the card require? Can you provide more details about it?

Size of the card is not fixed. please make the changes in styling giving the same class/id to each card div. Also, add some hover styling effects to the cards.
