### ISSUE TITLE
enhance the navbar

### ISSUE THREAD

**Issue by suhani1804** [CareerDevelopmentHub/SocialHub#4]

**Comment by TheChaoticor** [comment]
i have submitted my contribution for hackathon 2023

**Comment by TheChaoticor** [comment]
Assign this issue to me

**Comment by suhani1804** [comment]
> Assign this issue to me

done

**Comment by suhani1804** [comment]
> i have submitted my contribution for hackathon 2023

Please use the command "git pull" and then change the navbar design. Do it as per the theme. Also try to add a screenshot as an attachment.

**Comment by TheChaoticor** [comment]
What is the details of the theme according to which you want me to design,
may I ask? I am actually not particularly familiar with it

**Comment by suhani1804** [comment]
https://hacktober2023socialhub.netlify.app/ please check the updated site for better understanding

**Comment by TheChaoticor** [comment]
Thanks, I'll check it out.
