### ISSUE TITLE
design a logo for website

### ISSUE THREAD

**Issue by suhani1804** [CareerDevelopmentHub/SocialHub#61]

**Comment by Akash7649** [comment]
Hey @suhani1804 I would like to design a logo for the website, so please assign me this issue under Hacktoberfest2023

**Comment by Shubh04tech** [comment]
Hi @suhani1804 I have designed a nice logo for your website and its looking good, so can you assign me for this issue.

**Comment by suhani1804** [comment]
@Shubh04tech @Akash7649 Both provide me the logo best one will be accepted

**Comment by Shubh04tech** [comment]
Ok

**Comment by DAddy-is-CODing2** [comment]
![socialhub-low-resolution-color-logo](https://github.com/CareerDevelopmentHub/SocialHub/assets/115344654/0f513c69-7612-4480-b5d3-0e00b9398c71)

I do have this logo idea, If you like it plz assign it to me

**Comment by suhani1804** [comment]
@Shubh04tech do the commit adding your logo. @DAddy-is-CODing2 Your logo does not go with the theme.

**Comment by Shubh04tech** [comment]
i have pulled request to you as #72 Logo please approve it. Thanks
