### ISSUE TITLE
Add a “Scroll to TOP” button

### ISSUE THREAD

**Issue by PrajwalGraj** [CareerDevelopmentHub/SocialHub#66]
**Describe the Feature**
I would like to add a “Scroll to TOP” button in the footer of this page.

**Behaviour**
On clicking the Button which will be in footer, scrolls the web page to the top section and this improves the user experience.

**Comment by PrajwalGraj** [comment]
@suhani1804 I would like to work on it, can you assign me this.

**Comment by suhani1804** [comment]
> @suhani1804 I would like to work on it, can you assign me this.

Appreciate your interest. Assigned to you.
